package com.exam.order.model;
// Generated Apr 13, 2019 12:26:04 AM by Hibernate Tools 5.1.10.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Food generated by hbm2java
 */
@Entity
@Table(name = "food", catalog = "food_order")
public class Food implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -425195425854858945L;
	private Integer id;
	private MenuCategory menucategory;
	private String foodName;
	private String foodcale;
	private String foodVendor;
	private String foodDescription;
	private short quantityInStock;
	private BigDecimal buyPrice;
	private BigDecimal tax;
	private BigDecimal msrp;
	private byte[] image;
//	private Set<OrderDetail> orderdetails = new HashSet<OrderDetail>(0);
	private String urlImage;

	public Food() {
	}

	public Food(MenuCategory menucategory, String foodName, String foodcale, String foodVendor, String foodDescription,
			short quantityInStock, BigDecimal buyPrice, BigDecimal tax, BigDecimal msrp) {
		this.menucategory = menucategory;
		this.foodName = foodName;
		this.foodcale = foodcale;
		this.foodVendor = foodVendor;
		this.foodDescription = foodDescription;
		this.quantityInStock = quantityInStock;
		this.buyPrice = buyPrice;
		this.tax = tax;
		this.msrp = msrp;
	}

	public Food(MenuCategory menucategory, String foodName, String foodcale, String foodVendor, String foodDescription,
			short quantityInStock, BigDecimal buyPrice, BigDecimal tax, BigDecimal msrp, byte[] image) {
		this.menucategory = menucategory;
		this.foodName = foodName;
		this.foodcale = foodcale;
		this.foodVendor = foodVendor;
		this.foodDescription = foodDescription;
		this.quantityInStock = quantityInStock;
		this.buyPrice = buyPrice;
		this.tax = tax;
		this.msrp = msrp;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menuCategoryId", nullable = false)
	public MenuCategory getMenucategory() {
		return this.menucategory;
	}

	public void setMenucategory(MenuCategory menucategory) {
		this.menucategory = menucategory;
	}

	@Column(name = "foodName", nullable = false, length = 70)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@Column(name = "foodcale", nullable = false, length = 10)
	public String getFoodcale() {
		return this.foodcale;
	}

	public void setFoodcale(String foodcale) {
		this.foodcale = foodcale;
	}

	@Column(name = "foodVendor", nullable = false, length = 50)
	public String getFoodVendor() {
		return this.foodVendor;
	}

	public void setFoodVendor(String foodVendor) {
		this.foodVendor = foodVendor;
	}

	@Column(name = "foodDescription", nullable = false, length = 65535)
	public String getFoodDescription() {
		return this.foodDescription;
	}

	public void setFoodDescription(String foodDescription) {
		this.foodDescription = foodDescription;
	}

	@Column(name = "quantityInStock", nullable = false)
	public short getQuantityInStock() {
		return this.quantityInStock;
	}

	public void setQuantityInStock(short quantityInStock) {
		this.quantityInStock = quantityInStock;
	}

	@Column(name = "buyPrice", nullable = false, precision = 10)
	public BigDecimal getBuyPrice() {
		return this.buyPrice;
	}

	public void setBuyPrice(BigDecimal buyPrice) {
		this.buyPrice = buyPrice;
	}

	@Column(name = "tax", nullable = false, precision = 10)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "MSRP", nullable = false, precision = 10)
	public BigDecimal getMsrp() {
		return this.msrp;
	}

	public void setMsrp(BigDecimal msrp) {
		this.msrp = msrp;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "urlImage", precision = 255)
	public String getUrlImage() {
		return urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	
}
