package com.exam.order.model;
// Generated Apr 13, 2019 12:26:04 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Menucategory generated by hbm2java
 */
@Entity
@Table(name = "menucategory", catalog = "food_order")
public class MenuCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5399172029937290116L;
	private Integer id;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;
	private Set<Food> foods = new HashSet<Food>(0);

	public MenuCategory() {
	}

	public MenuCategory(String textDescription, String htmlDescription, byte[] image, Set<Food> foods) {
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
		this.foods = foods;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "menucategory")
	public Set<Food> getFoods() {
		return this.foods;
	}

	public void setFoods(Set<Food> foods) {
		this.foods = foods;
	}

}
