package com.exam.order.model;
// Generated Apr 13, 2019 12:26:04 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderdetailId generated by hbm2java
 */
@Embeddable
public class OrderdetailId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6042669211602219058L;
	private int id;
	private int foodId;

	public OrderdetailId() {
	}

	public OrderdetailId(int id, int foodId) {
		this.id = id;
		this.foodId = foodId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "foodId", nullable = false)
	public int getFoodId() {
		return this.foodId;
	}

	public void setFoodId(int foodId) {
		this.foodId = foodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderdetailId))
			return false;
		OrderdetailId castOther = (OrderdetailId) other;

		return (this.getId() == castOther.getId()) && (this.getFoodId() == castOther.getFoodId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getFoodId();
		return result;
	}

}
